// 02-mini-spa/react-screen/src/App.js
import React, {Component} from 'react';
import logo from './logo.svg';

class App extends Component {
  render() {
    return (
      <div>

        <h1>
          My Great Business App
        </h1>

        <h3>Provided by React</h3>

        <a href="http://localhost:4203/">Go to final screen ...</a>
        <br/>
        <a href="http://localhost:4201/">Back to first screen ...</a>

        <img src={logo} />

      </div>
    );
  }
}

export default App;

// 02-mini-spa/angular-screen/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-screen';
}

<div>


  <h1>
    My Great Business App
  </h1>

  <h3>Provided by Angular</h3>

  <a href="http://localhost:4202/">Go to second screen ...</a>

  <br>

  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
